[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "google-cloud-storage>=3.3.1",
    "googletrans==4.0.0rc1",
]
